### ISSUE TITLE
"Unknown error" in Firefox extension

### ISSUE THREAD

**Issue by funnelfactory** [Step7750/CSGOFloat-Extension#10]
Since yesterday, June 7 2018, the extension returns the message "Unknown error" in Firefox.

**Comment by funnelfactory** [comment]
It seems to be working now when I tried it even though the extension has not been updated. I'm confused now. I'll keep it open for now just in case. Thanks for the extension.

**Comment by Step7750** [comment]
This was due to the SSL certificate expiring, it should be fixed!
