### ISSUE TITLE
Sort items in the listing table by float value

### ISSUE THREAD

**Issue by bmwalters** [Step7750/CSGOFloat-Extension#2]

**Comment by Step7750** [comment]
I think if we have highlighting to the user's preference in #3, sorting the listings is kind of redundant. We'd also have to deal with [SIH](https://chrome.google.com/webstore/detail/steam-inventory-helper/cmeakgjggjdlcpncigglobpjbkabhmjl?hl=en) and the crazy functions it overwrites and making sure it doesn't break it.

**Comment by Step7750** [comment]
As stated earlier, not needed anymore due to #15
