### ISSUE TITLE
Sorting does not work anymore

### ISSUE THREAD

**Issue by roswell67** [Step7750/CSGOFloat-Extension#27]
As of today, the sorting no longer works. I tried reinstalling and it's still the same thing. Not sure what changed in the steam store that broke the functionality.

**Comment by Step7750** [comment]
I'm not able to replicate this on Chrome 73.0.3683.86, v1.3.1, Mac OS

Do you have any other Steam related extensions that could conflict?
What's your environment?

**Comment by roswell67** [comment]
Weird, it just started working again..... let me try to replicate

**Comment by roswell67** [comment]
OH! Found the bug. It's when you click on an item you listed, then you try to sort on that page.

![image](https://user-images.githubusercontent.com/10183897/54950882-606ac280-4f53-11e9-855b-bec8f76080b6.png)


Then into one of the items..


![image](https://user-images.githubusercontent.com/10183897/54950926-7bd5cd80-4f53-11e9-9485-96644adad332.png)


You can see that i clicked sort, but it doesn't function, I believe that page has different elements..

**Comment by roswell67** [comment]
Another update.. this is the console output (exception)

![image](https://user-images.githubusercontent.com/10183897/54951091-dbcc7400-4f53-11e9-80df-d359c763e1de.png)

**Comment by Step7750** [comment]
Looks like it needs a more specific selector, thanks for the report.

**Comment by Step7750** [comment]
A fix was merged to master, it'll be included in the next release.

**Comment by roswell67** [comment]
Thanks for the quick fix :) Would love it if you released it now so i could update 👍 ❤️

**Comment by Step7750** [comment]
Published in v1.3.2, it'll take some time to propagate.
