### ISSUE TITLE
Bug at the top of the application

### ISSUE THREAD

**Issue by w1g1** [Step7750/CSGOFloat-Extension#50]
Going through the report here, the top bar is duplicated both the banner and the box to enter the commands, thank

capture:
[http://oi64.tinypic.com/15y9mx3.jpg](url)

**Comment by Step7750** [comment]
Could you please give details on your browser and what version of the extension you're running? What other steam extensions are running?

**Comment by w1g1** [comment]
with pleasure: Google Chrome Versión 73.0.3683.103 / CSGOFloat Market Checker 2.0.2

**Comment by Step7750** [comment]
Does this happen on all pages? What other extensions do you have installed?

**Comment by w1g1** [comment]
only this application I have installed, if it happens almost in all pages, not many times but if it happens, that's why I tell you that it is like a bug that has a certain time in a sample of skins.

**Comment by Step7750** [comment]
Could you clone the branch `duplicate-utility` and see if that fixes it? https://github.com/Step7750/CSGOFloat-Extension/tree/fix/duplicate-utility

You can just download the zip and then load an unpacked extension in Chrome (enable developer mode in the top right)

If not, I'll just go forward with pushing it into a release.

**Comment by w1g1** [comment]
now checking, I see what happens is when you have several pages of open skin and update one after another by (F5) test and see if the same thing happens to you, that's when the double header bug comes up

**Comment by Step7750** [comment]
I've been able to reproduce it after loading 40 tabs at once, it is due to the page replying slower than normal to message queries from the extension.

The duplicate-utility branch should fix this and will be deployed into v2.0.3 in the next hour or so.

**Comment by w1g1** [comment]
perfect I will proceed as you told me not to be, I hope version 2.0.3, thanks and excellent application, I hope you can contribute ideas, bug and errors.
