### ISSUE TITLE
Duration from 35 sec to 1 minutes new skins

### ISSUE THREAD

**Issue by w1g1** [Step7750/CSGOFloat-Extension#59]
I am seeing that a new published skin or knife lasts, it takes about 30 seconds to 1 minute, which its estimated time to leave should be 5 to 10 seconds, please check it to see if it is an incompatibility or error with steam, thanks

**Comment by Step7750** [comment]
If this is only when you set page size to 100, that's due to different cache policies on Valve's end.

**Comment by w1g1** [comment]
If I actually use 100, with 50 it does not happen? have you tested?

**Comment by Step7750** [comment]
I believe so, does it happen for you?

**Comment by w1g1** [comment]
in 50 the slowness persists when leaving the skin or knife published

**Comment by w1g1** [comment]
good day now there is an error in listing 50 and 100> There was an error getting listings for this item. Please try again later.

**Comment by Step7750** [comment]
That's all Valve's issue, not the extension.
