### ISSUE TITLE
Quick buy feature

### ISSUE THREAD

**Issue by ueberchild** [Step7750/CSGOFloat-Extension#67]
SIH extension for Google Chrome has this very convenient "one-click buy" feature. How about adding to FF, maybe as an another addon? Actually on Steam Market you need to click 3 buttons for 1 buying, this is very slow. Also Augmented Steam (Enhanced Steam continuation) has quick sell button, but it's not so needed, it's better to look at the chart and choose a more suitable price.

**Comment by Step7750** [comment]
The extension thus far has had a philosophy of doing one thing well (and some more).

There are many possible things that could be implemented such as this, but it will likely increase false positive rates of buying items and I'd rather not have to deal with that.
