### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by AidarSource** [Step7750/CSGOFloat-Extension#76]
Unknown Error when i try to take float of weapon. Any weapon of Steam-market gets same error
![image](https://user-images.githubusercontent.com/34319725/71742500-35bb7c00-2e8c-11ea-84b2-db692a08a892.png)

**Comment by AidarSource** [comment]
version 2.2.1

**Comment by Step7750** [comment]
Hey, it'd be great if you could provide a network trace:

1) Go to chrome://extensions/?id=jjicbefpemnphinccgikpdaagjebbnhg
2) Inspect Views -> Background Page
3) Load a Steam Market Page with Float Values
4) Take a screenshot of the Network Tab and Paste it Here

**Comment by Step7750** [comment]
I think this may be due to the Cloudflare IP you're being routed through being banned by Russia's blocklist (https://blocklist.rkn.gov.ru/) if you're in that region.

**Comment by AidarSource** [comment]
![image](https://user-images.githubusercontent.com/34319725/71749752-84731100-2ea0-11ea-83af-a0e7834304b9.png)

**Comment by Step7750** [comment]
That is the network tab of the Steam page, not the extension.

Please follow the directions I gave earlier, starting with going to chrome://extensions/?id=jjicbefpemnphinccgikpdaagjebbnhg while you have the extension installed.

**Comment by AidarSource** [comment]
![image](https://user-images.githubusercontent.com/34319725/71749932-10853880-2ea1-11ea-81bb-ba874db9677b.png)

**Comment by Step7750** [comment]
Please turn on "developer mode" in the top right and then click the "Inspect Views" -> "Background Page"

**Comment by AidarSource** [comment]
![image](https://user-images.githubusercontent.com/34319725/71750474-aff6fb00-2ea2-11ea-82c1-427a66786c00.png)

**Comment by Step7750** [comment]
Great, now just click on the "Network" tab in that window and then try to view a steam market item page.

**Comment by AidarSource** [comment]
![image](https://user-images.githubusercontent.com/34319725/71750579-2136ae00-2ea3-11ea-81c4-226171b42851.png)

**Comment by Step7750** [comment]
Please take a screenshot of the network tab of the extension that you opened previously. (Ex. Inspect View -> Background Page -> Network Tab). That contains the requests that the extension sends, not the steam market page.

**Comment by AidarSource** [comment]
![image](https://user-images.githubusercontent.com/34319725/71750736-8d191680-2ea3-11ea-9b13-de3a9ed50964.png)

**Comment by Step7750** [comment]
Great! Could you click on one of the requests that has a status of "failed" and then send the details?

**Comment by AidarSource** [comment]
![image](https://user-images.githubusercontent.com/34319725/71750834-d1a4b200-2ea3-11ea-87ab-32a34f15895b.png)
![image](https://user-images.githubusercontent.com/34319725/71750840-dcf7dd80-2ea3-11ea-907a-59a9cba25338.png)

**Comment by Step7750** [comment]
Could you try loading this URL in your browser? https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198097456059A16436767615D19738985192562786

**Comment by Step7750** [comment]
If it fails to load, then unfortunately the Cloudflare IP you're connecting through is banned in Russia.

**Comment by AidarSource** [comment]
no, i cant. So sad, tomorrow i try with vpn or with one hack chrome command. I think its not only Russia, all CIS get ban, im from Kazakhstan

**Comment by AidarSource** [comment]
anyway thanks!

**Comment by AidarSource** [comment]
Is it safe to use vpn with your extension? Are there any chances for steam account steal?

**Comment by Step7750** [comment]
It's fine with our extension, your account should be safe, but you may want to make sure the VPN you use is reputable.
