### ISSUE TITLE
sometimes I can't switch to the next page

### ISSUE THREAD

**Issue by omarmsn** [Step7750/CSGOFloat-Extension#77]
first of all thanks a lot for the extension, but sometimes I get stuck at the same page I'm in, and refresh doesn't help, as well as it displays 10 items instead of 100. 
It will also be great if there was a filter that can hide the unwanted floats and prices to save more time

note: there is no other steam extention installed, and the issue happens on both Yandex and Chrome browser, and the issue get fixed by itself in few minutes (without even refreshing the page as if it is a sever issue idk), but it happens so often

**Comment by Step7750** [comment]
Hey, thanks for the report.

How often does this occur? I'll need some details about the exact steps you take in order to cause it, since I can't replicate it and this is the first report I've seen like this.

**Comment by omarmsn** [comment]
How often does this occur?
too often
steps: I open multiple tabs each shows 100 items, and that's it. (not every single time however it's like 1 out of 3 or 4) and also I open these pages from csgostash.com
when the issue happens I can't switch pages of the already opened 100 items tabs and any new tab will display just 10 items, and won't be switchable as well, after like 5 mins everything goes back to normal even for the currently opened tabs (the opened 10 items tabs will show 100 with a refresh or page switch)
note: even during that issue the extension shows the floats

**Comment by Step7750** [comment]
Thanks for those details!

I was able to replicate your issue by opening 20 SCM market pages in a short time period. It looks like you're simply hitting Steam's rate limit for opening pages (i.e. you opened too many pages at once), so you have to wait for the cooldown. Unfortunately this is an error related to Steam and not the extension (nor is there something that can be done from our end).

**Comment by omarmsn** [comment]
oh! well.. thanks a lot @Step7750
